// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grpzvouozarfociweami.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdycHp2b3VvemFyZm9jaXdlYW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MzA3NTUsImV4cCI6MjA3MDIwNjc1NX0.fcSDstRGiULv1tzfap12eTMP54x6jOOd7OdTfH3K8WU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});